directories:
  output: release
  buildResources: build
appId: com.agent4j.desktop
productName: Agent4j
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/favicon.ico
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: public/favicon.icns
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: public/favicon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 28.3.3
