package site.sorghum.loopra.web.service;

import lombok.extern.slf4j.Slf4j;
import org.noear.snack4.ONode;
import org.noear.solon.ai.chat.ChatModel;
import org.noear.solon.ai.chat.ChatResponse;
import org.noear.solon.annotation.Component;
import org.noear.solon.annotation.Inject;
import site.sorghum.loopra.bin.config.ConfigService;
import site.sorghum.loopra.bin.config.LoopraConfig;
import site.sorghum.loopra.bin.model.ModelContextUtils;
import site.sorghum.loopra.web.common.ServiceException;
import site.sorghum.loopra.web.common.entity.ProcessResult;
import site.sorghum.loopra.web.model.*;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.*;

/**
 * Git 操作服务 —— 封装所有 Git 命令执行逻辑、工作区解析和数据处理。
 * <p>
 * 提供 Git 状态查看、仓库初始化、暂存/取消暂存、提交、
 * Diff 内容查看及历史版本文件内容获取等完整的 Git 管理能力。
 * </p>
 *
 * @author Sorghum
 */
@Slf4j
@Component
public class GitService {

    @Inject
    private AgentService agentService;

    @Inject
    private ConfigService configService;

    // ==================== 常量 ====================

     /** status --porcelain 格式每行最小长度 (XY filename 至少 4 字符) */
    private static final int MIN_STATUS_LINE_LENGTH = 4;
    /** 单文件 diff 最大行数（超出截断） */
    private static final int MAX_DIFF_LINES = 2000;
    /** 生成提交消息时，每个文件 diff 最大行数 */
    private static final int MAX_DIFF_LINES_PER_FILE = 100;
    /** 生成提交消息时参考的近期提交条数 */
    private static final int RECENT_COMMIT_LOG_COUNT = 3;
    /** Git 命令超时秒数 */
    private static final int GIT_COMMAND_TIMEOUT_SEC = 10;
    /** 单个 Git 输出流在内存中保留的最大字符数 */
    private static final int MAX_GIT_OUTPUT_CHARS = 10 * 1024 * 1024;
    /** 命令结束后等待输出流消费完成的最大秒数 */
    private static final int GIT_OUTPUT_DRAIN_TIMEOUT_SEC = 1;
    /** Git 子进程的标准输出与错误输出必须并发消费，避免管道缓冲区写满。 */
    private static final ExecutorService GIT_IO_EXECUTOR = Executors.newCachedThreadPool(runnable -> {
        Thread thread = new Thread(runnable, "loopra-git-io");
        thread.setDaemon(true);
        return thread;
    });
    /** 默认 Git 提交作者名 */
    private static final String DEFAULT_AUTHOR_NAME = "Loopra";
    /** 默认 Git 提交作者邮箱 */
    private static final String DEFAULT_AUTHOR_EMAIL = "loopra@sorghum.site";

    /** 自动生成的 .gitignore 模板 */
    private static final String DEFAULT_GITIGNORE = String.join("\n",
            "# Auto-generated by " + DEFAULT_AUTHOR_NAME,
            ".git/",
            ".idea/",
            ".soloncode/",
            ".gradle/",
            ".mvn/",
            "node_modules/",
            "target/",
            "build/",
            "__pycache__/",
            "*.class",
            "*.jar",
            "*.log"
    );

    // ==================== 公开方法 ====================

    /**
     * 获取当前 Git 分支名称。
     */
    public String getBranch(String workspaceHash) {
        String workspacePath = resolveWorkspace(workspaceHash);
        String branch = runGitSimple(workspacePath, "rev-parse", "--abbrev-ref", "HEAD");
        if (branch == null) {
            throw new ServiceException("无法获取 Git 分支信息，目录可能不是 Git 仓库");
        }
        return branch.trim();
    }

    /**
     * 获取 Git 变更文件列表（暂存、未暂存和未跟踪）。
     */
    public GitDiffDTO getDiff(String workspaceHash) {
        String workspacePath = resolveWorkspace(workspaceHash);

        String branch = runGitSimple(workspacePath, "rev-parse", "--abbrev-ref", "HEAD");
        String raw = runGitSimple(workspacePath, "status", "--porcelain");

        List<GitFileChangeDTO> changed = new ArrayList<>();
        List<GitFileChangeDTO> untracked = new ArrayList<>();
        parsePorcelainStatus(raw, changed, untracked);

        return new GitDiffDTO(
                branch != null ? branch.trim() : "unknown",
                changed, untracked,
                changed.size() + untracked.size()
        );
    }

    /**
     * Git 综合状态检测 —— 四阶段检测：git 可用性 → 仓库状态 → 分支名 → 变更文件。
     */
    public GitStatusDTO getStatus(String workspaceHash) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 1. 检测 git 是否可用
        try {
            ProcessResult checkGit = runGit(workspaceDir, "git", "--version");
            if (checkGit.exitCode != 0) {
                return new GitStatusDTO(false, false, null,
                        workspaceDir.getAbsolutePath(), List.of(), List.of(), null, null);
            }
        } catch (Exception e) {
            return new GitStatusDTO(false, false, null,
                    workspaceDir.getAbsolutePath(), List.of(), List.of(), null, null);
        }

        // 2. 检测是否是 git 仓库
        ProcessResult checkRepo = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (checkRepo.exitCode != 0) {
            return new GitStatusDTO(true, false, null,
                    workspaceDir.getAbsolutePath(), List.of(), List.of(), null, null);
        }

        // 3. 获取分支名
        ProcessResult branchResult = runGit(workspaceDir, "git", "branch", "--show-current");
        String branch = branchResult.stdout.trim();
        if (branch.isEmpty()) branch = "master";

        // 4. 解析 git status --porcelain=v1
        ProcessResult statusResult = runGit(workspaceDir, "git", "status", "--porcelain=v1");
        List<GitFileChangeDTO> changed = new ArrayList<>();
        List<GitFileChangeDTO> untracked = new ArrayList<>();
        parsePorcelainStatus(statusResult.stdout, changed, untracked);

        // 5. 获取配置的模型与渠道
        Map<String, String> config = getGitConfig(workspaceHash);
        String model = config.get("model");
        String modelChannelId = config.get("modelChannelId");

        return new GitStatusDTO(true, true, branch,
                workspaceDir.getAbsolutePath(), changed, untracked, model, modelChannelId);
    }

    /**
     * 解析 git status --porcelain 输出，将结果填充到 changed 和 untracked 列表中。
     * <p>
     * 自动处理重命名（R old -> new）、带引号文件名和尾部斜杠。
     * </p>
     */
    private void parsePorcelainStatus(String porcelainOutput,
                                       List<GitFileChangeDTO> changed,
                                       List<GitFileChangeDTO> untracked) {
        if (porcelainOutput == null || porcelainOutput.trim().isEmpty()) return;
        for (String line : porcelainOutput.split("\n")) {
            if (line.trim().isEmpty() || line.length() < MIN_STATUS_LINE_LENGTH) continue;

            String indexStatus = String.valueOf(line.charAt(0));
            String workStatus = String.valueOf(line.charAt(1));
            String filename = line.substring(3).trim();

            // 处理重命名：R  old -> new
            if (filename.contains(" -> ")) {
                String[] parts = filename.split(" -> ", 2);
                filename = parts[1];
            }

            // 去掉文件名前后的引号
            if (filename.startsWith("\"") && filename.endsWith("\"")) {
                filename = filename.substring(1, filename.length() - 1);
            }

            // 去掉尾部斜杠
            if (filename.endsWith("/")) {
                filename = filename.substring(0, filename.length() - 1);
            }

            if ("?".equals(indexStatus) && "?".equals(workStatus)) {
                untracked.add(new GitFileChangeDTO(filename, indexStatus, workStatus, "U"));
            } else {
                String status = !" ".equals(indexStatus) && !"?".equals(indexStatus) ? indexStatus : workStatus;
                changed.add(new GitFileChangeDTO(filename, indexStatus, workStatus, status));
            }
        }
    }

    /**
     * 获取 Git Diff 内容 —— 分别执行未暂存变更和已暂存变更的 diff 查询，合并输出。
     * 对于未跟踪文件，返回文件内容作为新增的 diff。
     * 如果非 Git 管理或没有 diff，返回文件原文内容。
     */
    public GitDiffContentDTO getDiffContent(String workspaceHash, String path) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：防止路径穿越
        path = validatePath(workspaceDir, path);

        boolean hasPath = path != null && !path.isEmpty();

        // 检查是否是 Git 仓库
        ProcessResult checkRepo = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        boolean isGitRepo = checkRepo.exitCode == 0;

        if (!isGitRepo) {
            // 非 Git 管理，返回原文内容
            return getOriginalContent(workspaceDir, path, hasPath);
        }

        // 未暂存的变更
        List<String> unstagedCmd = new ArrayList<>(Arrays.asList("git", "diff"));
        if (hasPath) { unstagedCmd.add("--"); unstagedCmd.add(path); }
        ProcessResult unstagedResult = runGit(workspaceDir, unstagedCmd.toArray(new String[0]));

        // 已暂存的变更
        List<String> stagedCmd = new ArrayList<>(Arrays.asList("git", "diff", "--cached"));
        if (hasPath) { stagedCmd.add("--"); stagedCmd.add(path); }
        ProcessResult stagedResult = runGit(workspaceDir, stagedCmd.toArray(new String[0]));

        // 合并 diff 输出
        String fullDiff = unstagedResult.stdout;
        if (!stagedResult.stdout.isEmpty()) {
            fullDiff += "\n" + stagedResult.stdout;
        }

        // 对于未跟踪文件，git diff 返回空，需要读取文件内容生成 diff
        if (hasPath && fullDiff.trim().isEmpty()) {
            // 检查文件是否未跟踪
            List<String> statusCmd = new ArrayList<>(Arrays.asList("git", "status", "--porcelain", "--", path));
            ProcessResult statusResult = runGit(workspaceDir, statusCmd.toArray(new String[0]));
            if (statusResult.exitCode == 0 && statusResult.stdout.trim().startsWith("??")) {
                // 文件未跟踪，读取文件内容生成 diff
                File file = resolveWorkspaceFile(workspaceDir, path).toFile();
                if (file.exists() && file.isFile()) {
                    try {
                        List<String> lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
                        int lineCount = lines.size();
                        // 限制最大行数
                        int maxLines = MAX_DIFF_LINES;
                        if (lineCount > maxLines) {
                            lines = lines.subList(0, maxLines);
                        }
                        StringBuilder diffBuilder = new StringBuilder();
                        diffBuilder.append("--- /dev/null\n");
                        diffBuilder.append("+++ b/").append(path).append("\n");
                        diffBuilder.append("@@ -0,0 +1,").append(lineCount).append(" @@\n");
                        for (String line : lines) {
                            diffBuilder.append("+").append(line).append("\n");
                        }
                        if (lineCount > maxLines) {
                            diffBuilder.append("\n... (文件过大，仅显示前 ").append(maxLines).append(" 行)");
                        }
                        fullDiff = diffBuilder.toString();
                    } catch (Exception e) {
                        // 读取失败，忽略
                        log.debug("[git] 读取未跟踪文件失败: {}", e.getMessage());
                    }
                }
            }
        }

        // 如果没有 diff 且指定了路径，返回原文内容
        if (hasPath && fullDiff.trim().isEmpty()) {
            return getOriginalContent(workspaceDir, path, true);
        }

        // 截断保护：单文件 diff 限制 2000 行
        if (hasPath) {
            String[] lines = fullDiff.split("\n");
            if (lines.length > MAX_DIFF_LINES) {
                fullDiff = String.join("\n", Arrays.copyOf(lines, MAX_DIFF_LINES))
                        + "\n\n... (差异过大，仅显示前 " + MAX_DIFF_LINES + " 行，请在终端查看完整 diff)";
            }
        }

        // stat 摘要
        List<String> statCmd = new ArrayList<>(Arrays.asList("git", "diff", "--stat"));
        if (hasPath) { statCmd.add("--"); statCmd.add(path); }
        ProcessResult statResult = runGit(workspaceDir, statCmd.toArray(new String[0]));

        List<String> statCachedCmd = new ArrayList<>(Arrays.asList("git", "diff", "--cached", "--stat"));
        if (hasPath) { statCachedCmd.add("--"); statCachedCmd.add(path); }
        ProcessResult statCachedResult = runGit(workspaceDir, statCachedCmd.toArray(new String[0]));

        String stat = statResult.stdout;
        if (!statCachedResult.stdout.isEmpty()) {
            stat += (stat.isEmpty() ? "" : "\n") + statCachedResult.stdout;
        }

        // 对于未跟踪文件，生成 stat 摘要
        if (hasPath && stat.trim().isEmpty()) {
            // 再次检查未跟踪状态（可能已被上面的 diff 处理）
            List<String> statusCmd2 = new ArrayList<>(Arrays.asList("git", "status", "--porcelain", "--", path));
            ProcessResult statusResult2 = runGit(workspaceDir, statusCmd2.toArray(new String[0]));
            if (statusResult2.exitCode == 0 && statusResult2.stdout.trim().startsWith("??")) {
                File file = resolveWorkspaceFile(workspaceDir, path).toFile();
                if (file.exists() && file.isFile()) {
                    try {
                        List<String> lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
                        int lineCount = lines.size();
                        stat = path + " | " + lineCount + " ++";
                    } catch (Exception e) {
                        // 忽略
                    }
                }
            }
        }

        return new GitDiffContentDTO(fullDiff, stat);
    }

    /**
     * 获取文件原文内容 —— 用于非 Git 管理或没有 diff 的情况。
     */
    private GitDiffContentDTO getOriginalContent(File workspaceDir, String path, boolean hasPath) {
        if (!hasPath) {
            // 没有指定路径，返回空内容
            return new GitDiffContentDTO("", "");
        }

        File file = resolveWorkspaceFile(workspaceDir, path).toFile();
        if (!file.exists() || !file.isFile()) {
            // 文件不存在，返回空内容
            return new GitDiffContentDTO("", "");
        }

        try {
            List<String> lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
            int lineCount = lines.size();
            String content = String.join("\n", lines);
            String stat = path + " | " + lineCount + " lines";
            return new GitDiffContentDTO(content, stat);
        } catch (Exception e) {
            log.debug("[git] 读取文件失败: {}", e.getMessage());
            return new GitDiffContentDTO("", "");
        }
    }

    /**
     * 获取 Git 仓库中指定版本的文件内容。
     */
    public GitFileContentDTO getFileContent(String workspaceHash, String path, String ref) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        path = validatePath(workspaceDir, path);
        if (path == null || path.isEmpty()) {
            throw new ServiceException("Invalid path");
        }
        if (ref == null || ref.isEmpty()) ref = "HEAD";

        ProcessResult result = runGit(workspaceDir, "git", "show", ref + ":" + path);

        if (result.exitCode != 0) {
            throw new ServiceException("File not found: " + result.stderr);
        }

        return new GitFileContentDTO(result.stdout);
    }

    /**
     * 读取工作区当前文件内容，用于前端代码预览，不依赖 Git 状态或提交历史。
     */
    public WorkingFileContentDTO getWorkingFileContent(String workspaceHash, String path) throws Exception {
        if (path == null || path.isBlank()) {
            throw new ServiceException("Invalid path");
        }

        java.nio.file.Path workspace = java.nio.file.Paths.get(resolveWorkspace(workspaceHash)).toAbsolutePath().normalize();
        String filePath = path.trim().replaceFirst(":\\d+$", "");
        java.nio.file.Path requested = java.nio.file.Paths.get(filePath);
        java.nio.file.Path file = (requested.isAbsolute() ? requested : workspace.resolve(requested)).normalize();
        if (!file.startsWith(workspace)) {
            throw new ServiceException("Invalid path");
        }
        if (!Files.isRegularFile(file)) {
            return new WorkingFileContentDTO(null, false, "当前工作区中未找到此文件，可能已移动或删除。");
        }
        if (Files.size(file) > 1024 * 1024) {
            return new WorkingFileContentDTO(null, true, "文件过大，无法预览（最大 1 MB）。");
        }
        return new WorkingFileContentDTO(Files.readString(file, StandardCharsets.UTF_8), true, null);
    }

    /**
     * 获取 Git 提交历史记录，默认返回最近 50 条。
     * <p>
     * 使用 git log 自定义格式输出，按提交时间倒序排列。
     * </p>
     */
    public GitCommitDTO.ListWrapper getCommitHistory(String workspaceHash, Integer limit) {
        String workspacePath = resolveWorkspace(workspaceHash);
        if (limit == null || limit <= 0) limit = 50;

        // 自定义格式: hash|shortHash|author|email|date|message
        // 使用 %x1F (Unit Separator) 作为字段分隔，避免消息中的特殊字符干扰
        String format = "%H%x1F%h%x1F%an%x1F%ae%x1F%ai%x1F%s";
        String raw = runGitSimple(workspacePath,
                "log", "-" + limit, "--format=" + format);

        List<GitCommitDTO> commits = new ArrayList<>();
        if (raw != null && !raw.trim().isEmpty()) {
            for (String line : raw.split("\n")) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split("\u001F", 6);
                if (parts.length < 6) continue;
                commits.add(new GitCommitDTO(
                        parts[0],   // hash (full)
                        parts[1],   // shortHash
                        parts[2],   // author
                        parts[3],   // email
                        parts[4],   // date (ISO 8601)
                        parts[5]    // message
                ));
            }
        }
        return new GitCommitDTO.ListWrapper(commits, commits.size());
    }

    /**
     * 初始化 Git 仓库 —— git init + 自动生成 .gitignore + 可选初始提交。
     */
    public Map<String, Object> initRepo(String workspaceHash, Boolean initialCommit) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认不是已有仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode == 0) {
            throw new ServiceException("Already a git repository");
        }

        // 执行 git init
        ProcessResult initResult = runGit(workspaceDir, "git", "init");
        if (initResult.exitCode != 0) {
            throw new ServiceException("git init failed: " + initResult.stderr);
        }

        // 自动生成 .gitignore（仅当文件不存在时）
        File gitignore = new File(workspaceDir, ".gitignore");
        if (!gitignore.exists()) {
            Files.writeString(gitignore.toPath(), DEFAULT_GITIGNORE, StandardCharsets.UTF_8);
        }

        // 可选：执行 initial commit
        if (Boolean.TRUE.equals(initialCommit)) {
            runGit(workspaceDir, "git", "add", "-A");
            runGit(workspaceDir, "git", "-c", "user.name=" + DEFAULT_AUTHOR_NAME,
                    "-c", "user.email=" + DEFAULT_AUTHOR_EMAIL,
                    "commit", "-m", "Initial commit");
        }

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("initialized", true);

        ProcessResult branchResult = runGit(workspaceDir, "git", "branch", "--show-current");
        String branch = branchResult.stdout.trim();
        data.put("branch", branch.isEmpty() ? "master" : branch);

        return data;
    }

    /**
     * Git 提交 —— 解析 body 中的 message 和 files，支持精确文件列表或全量 add -A。
     */
    public GitCommitResultDTO commit(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认是 git 仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        // 解析 JSON body
        ONode json = parseJsonBody(body, "commit");
        String message = readStringField(json, "message");
        List<String> files = readStringListField(json, "files");
        String authorName = readStringField(json, "authorName");
        String authorEmail = readStringField(json, "authorEmail");

        if (message == null || message.trim().isEmpty()) {
            throw new ServiceException("Commit message is required");
        }

        // git add：有指定文件时精确暂存，否则只提交已暂存的文件
        if (files != null && !files.isEmpty()) {
            files = validatePaths(workspaceDir, files);
            // 先清空暂存区，避免之前已暂存的非选中文件被一起提交
            runGit(workspaceDir, "git", "reset", "HEAD", "--");

            List<String> addCmd = new ArrayList<>();
            addCmd.add("git");
            addCmd.add("add");
            addCmd.add("--");
            addCmd.addAll(files);
            ProcessResult addResult = runGit(workspaceDir, addCmd.toArray(new String[0]));
            if (addResult.exitCode != 0) {
                throw new ServiceException("git add failed: " + addResult.stderr);
            }
        }

        // 构建 git commit 命令（动态 author）
        List<String> commitCmd = new ArrayList<>();
        commitCmd.add("git");
        commitCmd.add("-c");
        commitCmd.add("user.name=" + (authorName != null && !authorName.trim().isEmpty() ? authorName.trim() : DEFAULT_AUTHOR_NAME));
        commitCmd.add("-c");
        commitCmd.add("user.email=" + (authorEmail != null && !authorEmail.trim().isEmpty() ? authorEmail.trim() : DEFAULT_AUTHOR_EMAIL));
        commitCmd.add("commit");
        commitCmd.add("-m");
        commitCmd.add(message);
        ProcessResult commitResult = runGit(workspaceDir, commitCmd.toArray(new String[0]));

        if (commitResult.exitCode != 0) {
            throw new ServiceException("git commit failed: " + commitResult.stderr);
        }

        return new GitCommitResultDTO(commitResult.stdout);
    }

    /**
     * 获取提交作者配置（优先级：已保存配置 > git config > Loopra 默认）。
     */
    public Map<String, String> getGitConfig(String workspaceHash) {
        String workspacePath = resolveWorkspace(workspaceHash);
        File workspaceDir = new File(workspacePath);

        Map<String, String> result = new LinkedHashMap<>();

        // 1) 读取已保存的 .loopra/git-author.json
        File configFile = new File(workspaceDir, ".loopra/git-author.json");
        if (configFile.exists()) {
            try {
                String json = Files.readString(configFile.toPath(), StandardCharsets.UTF_8);
                ONode node = ONode.ofJson(json);
                if (node != null && node.isObject()) {
                    ONode nameNode = node.get("authorName");
                    if (nameNode != null && nameNode.isString() && !nameNode.getString().trim().isEmpty()) {
                        result.put("authorName", nameNode.getString().trim());
                    }
                    ONode emailNode = node.get("authorEmail");
                    if (emailNode != null && emailNode.isString() && !emailNode.getString().trim().isEmpty()) {
                        result.put("authorEmail", emailNode.getString().trim());
                    }
                    ONode modelNode = node.get("model");
                    if (modelNode != null && modelNode.isString() && !modelNode.getString().trim().isEmpty()) {
                        result.put("model", modelNode.getString().trim());
                    }
                    ONode channelNode = node.get("modelChannelId");
                    if (channelNode != null && channelNode.isString() && !channelNode.getString().trim().isEmpty()) {
                        result.put("modelChannelId", channelNode.getString().trim());
                    }
                }
            } catch (Exception e) {
                log.debug("[git] 读取 git-author.json 失败: {}", e.getMessage());
            }
        }

        // 2) 已保存配置缺少的字段，从 git config 补充
        if (!result.containsKey("authorName") || result.get("authorName") == null || result.get("authorName").isEmpty()) {
            String name = runGitSimple(workspacePath, "config", "user.name");
            if (name != null && !name.trim().isEmpty()) {
                result.put("authorName", name.trim());
            }
        }
        if (!result.containsKey("authorEmail") || result.get("authorEmail") == null || result.get("authorEmail").isEmpty()) {
            String email = runGitSimple(workspacePath, "config", "user.email");
            if (email != null && !email.trim().isEmpty()) {
                result.put("authorEmail", email.trim());
            }
        }

        // 3) 仍缺失的字段，回退到 Loopra 默认值
        if (!result.containsKey("authorName") || result.get("authorName") == null || result.get("authorName").isEmpty()) {
            result.put("authorName", DEFAULT_AUTHOR_NAME);
        }
        if (!result.containsKey("authorEmail") || result.get("authorEmail") == null || result.get("authorEmail").isEmpty()) {
            result.put("authorEmail", DEFAULT_AUTHOR_EMAIL);
        }

        // 4) 模型字段：如果未配置，使用当前全局模型
        if (!result.containsKey("model") || result.get("model") == null || result.get("model").isEmpty()) {
            result.put("model", agentService.getSharedModel());
        }
        // 4.1) 模型渠道字段：如果未配置，回退到当前激活渠道
        if (!result.containsKey("modelChannelId") || result.get("modelChannelId") == null || result.get("modelChannelId").isEmpty()) {
            LoopraConfig cfg = ConfigService.getConfig();
            if (cfg != null) {
                result.put("modelChannelId", cfg.modelChannelId());
            }
        }

        return result;
    }

    /**
     * 保存提交作者配置到 .loopra/git-author.json。
     */
    public Map<String, String> saveGitConfig(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 解析 body
        ONode json = parseJsonBody(body, "saveGitConfig");
        String authorName = readStringField(json, "authorName");
        String authorEmail = readStringField(json, "authorEmail");
        String model = readStringField(json, "model");
        String modelChannelId = readStringField(json, "modelChannelId");
        if (authorName == null || authorEmail == null) {
            throw new ServiceException("作者名和邮箱不能为空");
        }

        // 确保 .loopra 目录存在
        File loopraDir = new File(workspaceDir, ".loopra");
        if (!loopraDir.exists()) {
            loopraDir.mkdirs();
        }

        // 写入 git-author.json
        File configFile = new File(loopraDir, "git-author.json");
        ONode configNode = ONode.ofJson("{}").asObject();
        configNode.set("authorName", authorName);
        configNode.set("authorEmail", authorEmail);
        if (model != null && !model.trim().isEmpty()) {
            configNode.set("model", model.trim());
        }
        if (modelChannelId != null && !modelChannelId.trim().isEmpty()) {
            configNode.set("modelChannelId", modelChannelId.trim());
        }
        Files.writeString(configFile.toPath(), configNode.toJson(), StandardCharsets.UTF_8);

        Map<String, String> result = new LinkedHashMap<>();
        result.put("authorName", authorName);
        result.put("authorEmail", authorEmail);
        if (model != null && !model.trim().isEmpty()) {
            result.put("model", model.trim());
        }
        if (modelChannelId != null && !modelChannelId.trim().isEmpty()) {
            result.put("modelChannelId", modelChannelId.trim());
        }
        return result;
    }

    /**
     * 切换文件状态：未追踪 → 变更（git add），或变更 → 未追踪（git reset HEAD --）。
     */
    public Map<String, Object> toggleFile(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        String path = validatePath(workspaceDir, extractPath(body));
        if (path == null) {
            throw new ServiceException("Path is required");
        }

        // 检查文件当前状态
        ProcessResult statusResult = runGit(workspaceDir, "git", "status", "--porcelain", "--", path);
        String statusLine = statusResult.stdout.trim();

        ProcessResult result;
        String newState;

        if (statusLine.isEmpty() || statusLine.startsWith("M") || statusLine.startsWith("A") ||
                statusLine.startsWith("D") || statusLine.startsWith("R")) {
            // 已暂存或已追踪的变更 → 取消暂存
            result = runGit(workspaceDir, "git", "reset", "HEAD", "--", path);
            newState = "untracked";
        } else if (statusLine.startsWith("?")) {
            // 未追踪 → 暂存
            result = runGit(workspaceDir, "git", "add", "--", path);
            newState = "changed";
        } else {
            // 其他情况（如  M 未暂存修改）→ 暂存
            result = runGit(workspaceDir, "git", "add", "--", path);
            newState = "changed";
        }

        if (result.exitCode != 0) {
            throw new ServiceException("git toggle failed: " + result.stderr);
        }

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("path", path);
        data.put("newState", newState);
        return data;
    }

    /**
     * AI 自动生成 Git 提交消息 —— 获取当前变更及近 10 条提交日志，调用 LLM 生成。
     */
    public GitGenerateMessageDTO generateCommitMessage(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认是 git 仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        // 解析请求体
        ONode bodyJson = parseJsonBody(body, "generateCommitMessage");
        List<String> files = readStringListField(bodyJson, "files");
        String requestModel = readStringField(bodyJson, "model");
        String requestChannelId = readStringField(bodyJson, "modelChannelId");

        if (files != null && !files.isEmpty()) {
            files = validatePaths(workspaceDir, files);
        }

        // 检查 AI 模型配置（默认走当前激活渠道，按请求/工作区配置的渠道覆盖）
        String apiUrl = agentService.getSharedApiUrl();
        String apiKey = agentService.getSharedApiKey();
        String model = agentService.getSharedModel();
        String channelId = null;
        if (apiUrl == null || apiKey == null || model == null) {
            throw new ServiceException("AI 模型未配置，请先设置 OPENAI_API_KEY 环境变量");
        }

        // 读取工作区配置的模型与渠道（优先使用请求参数 > 工作区配置 > 全局配置）
        Map<String, String> workspaceConfig = getGitConfig(workspaceHash);
        if (requestModel != null && !requestModel.trim().isEmpty()) {
            model = requestModel.trim();
            channelId = requestChannelId;
            // 持久化模型与渠道配置
            saveGitConfig(workspaceHash, ONode.ofJson("{}")
                    .set("authorName", workspaceConfig.get("authorName"))
                    .set("authorEmail", workspaceConfig.get("authorEmail"))
                    .set("model", model)
                    .set("modelChannelId", channelId != null ? channelId : "")
                    .toJson());
        } else {
            String configModel = workspaceConfig.get("model");
            if (configModel != null && !configModel.trim().isEmpty()) {
                model = configModel.trim();
            }
            channelId = workspaceConfig.get("modelChannelId");
        }

        // 按指定渠道覆盖 apiUrl/apiKey（实现多渠道真正按渠道调用）
        if (channelId != null && !channelId.trim().isEmpty()) {
            LoopraConfig cfg = ConfigService.getConfig();
            if (cfg != null) {
                LoopraConfig.ModelChannel channel = cfg.modelChannel(channelId.trim());
                if (channel != null && !channel.baseUrl().isBlank()) {
                    String base = channel.baseUrl();
                    apiUrl = base.endsWith("/") ? base + "chat/completions" : base + "/chat/completions";
                    if (!channel.apiKey().isBlank()) {
                        apiKey = channel.apiKey();
                    }
                }
            }
        }

        // 构建 Solon ChatModel（轻量、无推理）
        // 剥离模型名称中的上下文大小后缀，例如 "mimo-v2.5[512k]" → "mimo-v2.5"
        ChatModel chatModel = ChatModel.of(apiUrl)
                .apiKey(apiKey)
                .model(ModelContextUtils.stripContextSizeSuffix(model))
                .modelOptions(o -> {
                    o.temperature(0.1);
                    o.optionSet("chat_template_kwargs", ONode.ofJson("{}").set("enable_thinking", false));
                    o.optionSet("enable_thinking",false);
                    o.optionSet("thinking",ONode.ofJson("{}").set("type","disabled"));
                })
                .build();

        // 1. 获取近 N 条提交日志（用于风格参考）
        String recentLog = runGitSimple(workspaceDir.getAbsolutePath(),
                "log", "--oneline", "-" + RECENT_COMMIT_LOG_COUNT);
        if (recentLog == null) recentLog = "";

        // 2. 如果没有指定文件，则从 git status 获取所有变更文件
        if (files == null || files.isEmpty()) {
            files = getChangedFiles(workspaceDir);
        }

        // 逐文件获取 diff，每个文件最多保留 MAX_DIFF_LINES_PER_FILE 行
        StringBuilder sb = new StringBuilder();
        for (String f : files) {
            String staged = "", unstaged = "";
            try {
                ProcessResult sr = runGit(workspaceDir, "git", "diff", "--cached", "--", f);
                if (sr.stdout != null && !sr.stdout.isEmpty()) staged = sr.stdout;
            } catch (Exception e) {
                log.debug("[git] 获取文件 {} 的 staged diff 失败: {}", f, e.getMessage());
            }
            try {
                ProcessResult ur = runGit(workspaceDir, "git", "diff", "--", f);
                if (ur.stdout != null && !ur.stdout.isEmpty()) unstaged = ur.stdout;
            } catch (Exception e) {
                log.debug("[git] 获取文件 {} 的 unstaged diff 失败: {}", f, e.getMessage());
            }
            String fileDiff = (staged + "\n" + unstaged).trim();
            if (!fileDiff.isEmpty()) {
                sb.append("# ").append(f).append("\n");
                sb.append(truncateLines(fileDiff, MAX_DIFF_LINES_PER_FILE)).append("\n\n");
            }
        }
        String fullDiff = sb.toString().trim();

        if (fullDiff.isEmpty()) {
            throw new ServiceException("没有待提交的变更");
        }

        // 3. 构建 AI 提示词
        String systemPrompt = """
                你是一个 Git 提交消息生成助手。\
                根据 git diff 内容生成一条简洁、描述性的提交消息。\
                严格遵循以下规约：
                - 参考「近 3 条提交」的风格（如前缀、格式、语言等）
                - 消息长度不超过 72 字符（中文不超过 50 字）
                - 使用中文或英文取决于近期提交的语言
                - 仅输出提交消息本身，不要任何解释、引号或 markdown 格式""";

        String userPrompt = "近 3 条提交（风格参考）：\n"
                + (recentLog.isEmpty() ? "（无历史提交）" : recentLog) + "\n\n"
                + "当前变更（git diff）：\n" + fullDiff + "\n\n"
                + "请生成提交消息：";

        // 4. 调用 AI 模型（使用 Solon ChatModel，简单直接）
        try {
            ChatResponse response = chatModel.prompt(userPrompt)
                    .options(o -> o.systemPrompt(systemPrompt))
                    .call();
            String content = response.getMessage().getResultContent();
            if (content == null || content.trim().isEmpty()) {
                throw new ServiceException("AI 未能生成提交消息");
            }
            // 清理多余的引号和空白
            String message = content.trim()
                    .replaceAll("^[\"']+|[\"']+$", "")
                    .replaceAll("^```[a-z]*\\s*|```$", "")
                    .trim();
            return new GitGenerateMessageDTO(message);
        } catch (Exception e) {
            log.error("[git] AI 生成提交消息失败: {}", e.getMessage());
            throw new ServiceException("AI 调用失败: " + e.getMessage());
        }
    }

    // ==================== 工具方法 ====================

    public String resolveWorkspace(String workspaceHash) {
        String workspacePath = agentService.resolveWorkspacePath(workspaceHash);
        if (workspacePath == null) workspacePath = agentService.getWorkspace();
        if (workspacePath == null) throw new ServiceException("未设置工作区");
        return workspacePath;
    }

    // ==================== 路径安全校验 ====================

    /**
     * 将请求路径规范化为工作区内的 Git 路径，并拒绝绝对路径、路径穿越和符号链接逃逸。
     * 空路径仅供查询整个仓库的接口使用。
     */
    private String validatePath(File workspaceDir, String path) {
        if (path == null) return null;
        String trimmed = path.trim();
        if (trimmed.isEmpty()) return "";

        Path file = resolveWorkspaceFile(workspaceDir, trimmed);
        return workspacePath(workspaceDir).relativize(file).toString().replace(File.separatorChar, '/');
    }

    private List<String> validatePaths(File workspaceDir, List<String> paths) {
        List<String> validated = new ArrayList<>(paths.size());
        for (String path : paths) {
            String value = validatePath(workspaceDir, path);
            if (value == null || value.isEmpty()) {
                throw new ServiceException("Invalid path");
            }
            validated.add(value);
        }
        return validated;
    }

    private Path resolveWorkspaceFile(File workspaceDir, String path) {
        try {
            Path workspace = workspacePath(workspaceDir);
            Path requested = Path.of(path);
            if (requested.isAbsolute()) {
                throw new ServiceException("Invalid path");
            }

            Path file = workspace.resolve(requested).normalize();
            if (!file.startsWith(workspace)) {
                throw new ServiceException("Invalid path");
            }

            // 对不存在的目标，验证最近的已有父目录，避免通过工作区内的链接目录逃逸。
            Path existing = file;
            while (existing != null && !Files.exists(existing, LinkOption.NOFOLLOW_LINKS)) {
                existing = existing.getParent();
            }
            if (existing == null || !existing.toRealPath().startsWith(workspace)) {
                throw new ServiceException("Invalid path");
            }
            return file;
        } catch (InvalidPathException | IOException e) {
            throw new ServiceException("Invalid path");
        }
    }

    private Path workspacePath(File workspaceDir) {
        try {
            return workspaceDir.toPath().toRealPath();
        } catch (IOException e) {
            throw new ServiceException("工作区不可访问");
        }
    }

    // ==================== AI 辅助工具方法 ====================

    /**
     * 获取工作区中所有变更文件列表（含暂存、未暂存、未跟踪）。
     */
    private List<String> getChangedFiles(File workspaceDir) throws Exception {
        ProcessResult result = runGit(workspaceDir, "git", "status", "--porcelain");
        if (result.exitCode != 0 || result.stdout == null || result.stdout.trim().isEmpty()) {
            return List.of();
        }
        List<String> fileList = new ArrayList<>();
        for (String line : result.stdout.split("\n")) {
            if (line.trim().isEmpty() || line.length() < MIN_STATUS_LINE_LENGTH) continue;
            String filename = line.substring(3).trim();
            // 处理重命名
            if (filename.contains(" -> ")) {
                filename = filename.split(" -> ", 2)[1];
            }
            if (filename.startsWith("\"") && filename.endsWith("\"")) {
                filename = filename.substring(1, filename.length() - 1);
            }
            if (!fileList.contains(filename)) {
                fileList.add(filename);
            }
        }
        return fileList;
    }

    /**
     * 截断文本到指定行数，超出时末尾添加截断提示。
     */
    private static String truncateLines(String text, int maxLines) {
        if (text == null || text.isEmpty()) return text;
        String[] lines = text.split("\n", -1);
        if (lines.length <= maxLines) return text;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < maxLines; i++) {
            sb.append(lines[i]).append("\n");
        }
        sb.append("... (diff 过长，截断至 ").append(maxLines).append(" 行)");
        return sb.toString();
    }

    // ==================== JSON 解析工具方法 ====================

    /**
     * 安全解析 JSON body 为 ONode 对象，解析失败时记录日志并返回 null。
     */
    private ONode parseJsonBody(String body, String caller) {
        if (body == null || body.trim().isEmpty()) return null;
        try {
            ONode json = ONode.ofJson(body);
            if (json != null && json.isObject()) return json;
        } catch (Exception e) {
            log.debug("[git] {} 解析 JSON body 失败: {}", caller, e.getMessage());
        }
        return null;
    }

    /**
     * 从 ONode 对象中安全读取字符串字段，缺失或类型不符时返回 null。
     */
    private String readStringField(ONode json, String field) {
        if (json == null) return null;
        ONode node = json.get(field);
        if (node != null && node.isString()) {
            String value = node.getString();
            return value != null && !value.trim().isEmpty() ? value.trim() : null;
        }
        return null;
    }

    /**
     * 从 ONode 对象中安全读取字符串数组字段，缺失或类型不符时返回 null。
     */
    private List<String> readStringListField(ONode json, String field) {
        if (json == null) return null;
        ONode node = json.get(field);
        if (node != null && node.isArray()) {
            List<String> list = new ArrayList<>();
            for (ONode item : node.getArray()) {
                if (item.isString()) list.add(item.getString());
            }
            return list.isEmpty() ? null : list;
        }
        return null;
    }

    /**
     * 从 JSON 请求体中提取 path 字段。
     */
    private String extractPath(String body) {
        ONode json = parseJsonBody(body, "extractPath");
        return readStringField(json, "path");
    }

    /**
     * 简单 Git 命令执行 —— 用于只读查询，基于 runGit 的薄包装。
     */
    private String runGitSimple(String dir, String... args) {
        try {
            List<String> cmd = new ArrayList<>();
            cmd.add("git");
            Collections.addAll(cmd, args);
            ProcessResult result = runGit(new File(dir), cmd.toArray(new String[0]));
            return result.exitCode == 0 ? result.stdout : null;
        } catch (Exception e) {
            log.warn("[git] 执行失败: {}", e.getMessage());
            return null;
        }
    }

    /**
     * 增强 Git 命令执行 —— 带 10 秒超时保护、禁用终端交互提示。
     */
    private ProcessResult runGit(File workDir, String... command) throws Exception {
        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(workDir);
        pb.redirectErrorStream(false);
        pb.environment().put("GIT_TERMINAL_PROMPT", "0");

        Process proc = pb.start();
        Future<String> stdout = GIT_IO_EXECUTOR.submit(() -> readStream(proc.getInputStream()));
        Future<String> stderr = GIT_IO_EXECUTOR.submit(() -> readStream(proc.getErrorStream()));
        try {
            boolean finished = proc.waitFor(GIT_COMMAND_TIMEOUT_SEC, TimeUnit.SECONDS);
            if (!finished) {
                proc.destroyForcibly();
                proc.waitFor();
                return processResult(-1, "", "Command timed out after " + GIT_COMMAND_TIMEOUT_SEC + " seconds");
            }

            return processResult(proc.exitValue(), awaitOutput(stdout), awaitOutput(stderr));
        } finally {
            if (proc.isAlive()) {
                proc.destroyForcibly();
            }
            stdout.cancel(true);
            stderr.cancel(true);
        }
    }

    private ProcessResult processResult(int exitCode, String stdout, String stderr) {
        ProcessResult result = new ProcessResult();
        result.exitCode = exitCode;
        result.stdout = stdout;
        result.stderr = stderr;
        return result;
    }

    private String awaitOutput(Future<String> output) throws Exception {
        return output.get(GIT_OUTPUT_DRAIN_TIMEOUT_SEC, TimeUnit.SECONDS);
    }

    private String readStream(InputStream input) throws IOException {
        StringBuilder output = new StringBuilder();
        try (input) {
            byte[] buffer = new byte[8192];
            int read;
            while ((read = input.read(buffer)) != -1) {
                String chunk = new String(buffer, 0, read, StandardCharsets.UTF_8);
                int remaining = MAX_GIT_OUTPUT_CHARS - output.length();
                if (remaining > 0) {
                    output.append(chunk, 0, Math.min(remaining, chunk.length()));
                }
            }
        }
        if (output.length() >= MAX_GIT_OUTPUT_CHARS) {
            output.append("\n... (Git output truncated)");
        }
        return output.toString();
    }


}
