package site.sorghum.agent4j.web.service;

import lombok.extern.slf4j.Slf4j;
import org.noear.snack4.ONode;
import org.noear.solon.annotation.Component;
import org.noear.solon.annotation.Inject;
import site.sorghum.agent4j.bin.agent.ChatMessage;
import site.sorghum.agent4j.bin.model.ModelClient;
import site.sorghum.agent4j.web.common.ServiceException;
import site.sorghum.agent4j.web.common.entity.ProcessResult;
import site.sorghum.agent4j.web.model.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.*;
import java.util.concurrent.TimeUnit;

/**
 * Git 操作服务 —— 封装所有 Git 命令执行逻辑、工作区解析和数据处理。
 * <p>
 * 提供 Git 状态查看、仓库初始化、暂存/取消暂存、提交、
 * Diff 内容查看及历史版本文件内容获取等完整的 Git 管理能力。
 * </p>
 *
 * @author Sorghum
 */
@Slf4j
@Component
public class GitService {

    @Inject
    private AgentService agentService;

    // ==================== 常量 ====================

    /** porcelain 格式每行最小长度 (XY filename) */
    private static final int MIN_PORCELAIN_LINE_LENGTH = 3;
    /** status --porcelain=v1 格式每行最小长度 */
    private static final int MIN_STATUS_LINE_LENGTH = 4;
    /** 单文件 diff 最大行数（超出截断） */
    private static final int MAX_DIFF_LINES = 2000;
    /** AI 生成提交消息时 diff 最大字符数 */
    private static final int MAX_DIFF_CHARS = 8000;
    /** 生成提交消息时参考的近期提交条数 */
    private static final int RECENT_COMMIT_LOG_COUNT = 10;
    /** Git 命令超时秒数 */
    private static final int GIT_COMMAND_TIMEOUT_SEC = 10;

    /** 自动生成的 .gitignore 模板 */
    private static final String DEFAULT_GITIGNORE = String.join("\n",
            "# Auto-generated by Agent4j",
            ".git/",
            ".idea/",
            ".soloncode/",
            ".gradle/",
            ".mvn/",
            "node_modules/",
            "target/",
            "build/",
            "__pycache__/",
            "*.class",
            "*.jar",
            "*.log"
    );

    // ==================== 公开方法 ====================

    /**
     * 获取当前 Git 分支名称。
     */
    public String getBranch(String workspaceHash) {
        String workspacePath = resolveWorkspace(workspaceHash);
        String branch = runGitSimple(workspacePath, "rev-parse", "--abbrev-ref", "HEAD");
        if (branch == null) {
            throw new ServiceException("无法获取 Git 分支信息，目录可能不是 Git 仓库");
        }
        return branch.trim();
    }

    /**
     * 获取 Git 变更文件列表（暂存、未暂存和未跟踪）。
     */
    public GitDiffDTO getDiff(String workspaceHash) {
        String workspacePath = resolveWorkspace(workspaceHash);

        String branch = runGitSimple(workspacePath, "rev-parse", "--abbrev-ref", "HEAD");
        String raw = runGitSimple(workspacePath, "status", "--porcelain");

        List<GitFileChangeDTO> changed = new ArrayList<>();
        List<GitFileChangeDTO> untracked = new ArrayList<>();

        if (raw != null && !raw.trim().isEmpty()) {
            for (String line : raw.split("\n")) {
                if (line.trim().isEmpty() || line.length() < MIN_PORCELAIN_LINE_LENGTH) continue;

                String indexStatus = String.valueOf(line.charAt(0));
                String workStatus = String.valueOf(line.charAt(1));
                String filename = line.substring(3).trim();

                if (filename.contains(" -> ")) {
                    String[] parts = filename.split(" -> ", 2);
                    filename = parts[1];
                }

                // 去掉文件名前后的引号（用于文件名包含空格的情况）
                if (filename.startsWith("\"") && filename.endsWith("\"")) {
                    filename = filename.substring(1, filename.length() - 1);
                }

                if (indexStatus.equals("?") && workStatus.equals("?")) {
                    untracked.add(new GitFileChangeDTO(filename, indexStatus, workStatus, "U"));
                } else {
                    String status = !indexStatus.equals(" ") && !indexStatus.equals("?") ? indexStatus : workStatus;
                    changed.add(new GitFileChangeDTO(filename, indexStatus, workStatus, status));
                }
            }
        }

        return new GitDiffDTO(
                branch != null ? branch.trim() : "unknown",
                changed, untracked,
                changed.size() + untracked.size()
        );
    }

    /**
     * Git 综合状态检测 —— 四阶段检测：git 可用性 → 仓库状态 → 分支名 → 变更文件。
     */
    public GitStatusDTO getStatus(String workspaceHash) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 1. 检测 git 是否可用
        try {
            ProcessResult checkGit = runGit(workspaceDir, "git", "--version");
            if (checkGit.exitCode != 0) {
                return new GitStatusDTO(false, false, null,
                        workspaceDir.getAbsolutePath(), List.of(), List.of());
            }
        } catch (Exception e) {
            return new GitStatusDTO(false, false, null,
                    workspaceDir.getAbsolutePath(), List.of(), List.of());
        }

        // 2. 检测是否是 git 仓库
        ProcessResult checkRepo = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (checkRepo.exitCode != 0) {
            return new GitStatusDTO(true, false, null,
                    workspaceDir.getAbsolutePath(), List.of(), List.of());
        }

        // 3. 获取分支名
        ProcessResult branchResult = runGit(workspaceDir, "git", "branch", "--show-current");
        String branch = branchResult.stdout.trim();
        if (branch.isEmpty()) branch = "master";

        // 4. 解析 git status --porcelain=v1
        ProcessResult statusResult = runGit(workspaceDir, "git", "status", "--porcelain=v1");
        List<GitFileChangeDTO> changed = new ArrayList<>();
        List<GitFileChangeDTO> untracked = new ArrayList<>();

        for (String line : statusResult.stdout.split("\n")) {
            if (line.length() < MIN_STATUS_LINE_LENGTH) continue;
            String x = line.substring(0, 1);
            String y = line.substring(1, 2);
            String filePath = line.substring(3).trim();

            // 处理重命名的情况：R  old -> new
            if (filePath.contains(" -> ")) {
                String[] parts = filePath.split(" -> ", 2);
                filePath = parts[1];
            }

            // 去掉文件名前后的引号（用于文件名包含空格的情况）
            if (filePath.startsWith("\"") && filePath.endsWith("\"")) {
                filePath = filePath.substring(1, filePath.length() - 1);
            }

            if (filePath.endsWith("/")) {
                filePath = filePath.substring(0, filePath.length() - 1);
            }

            if ("?".equals(x) && "?".equals(y)) {
                untracked.add(new GitFileChangeDTO(filePath, x, y, "U"));
            } else {
                String status = !" ".equals(x) && !"?".equals(x) ? x : y;
                changed.add(new GitFileChangeDTO(filePath, x, y, status));
            }
        }

        return new GitStatusDTO(true, true, branch,
                workspaceDir.getAbsolutePath(), changed, untracked);
    }

    /**
     * 获取 Git Diff 内容 —— 分别执行未暂存变更和已暂存变更的 diff 查询，合并输出。
     */
    public GitDiffContentDTO getDiffContent(String workspaceHash, String path) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：防止路径穿越
        if (path != null && (path.contains("..") || path.startsWith("/"))) {
            throw new ServiceException("Invalid path");
        }

        boolean hasPath = path != null && !path.trim().isEmpty();

        // 未暂存的变更
        List<String> unstagedCmd = new ArrayList<>(Arrays.asList("git", "diff"));
        if (hasPath) { unstagedCmd.add("--"); unstagedCmd.add(path); }
        ProcessResult unstagedResult = runGit(workspaceDir, unstagedCmd.toArray(new String[0]));

        // 已暂存的变更
        List<String> stagedCmd = new ArrayList<>(Arrays.asList("git", "diff", "--cached"));
        if (hasPath) { stagedCmd.add("--"); stagedCmd.add(path); }
        ProcessResult stagedResult = runGit(workspaceDir, stagedCmd.toArray(new String[0]));

        // 合并 diff 输出
        String fullDiff = unstagedResult.stdout;
        if (!stagedResult.stdout.isEmpty()) {
            fullDiff += "\n" + stagedResult.stdout;
        }

        // 截断保护：单文件 diff 限制 2000 行
        if (hasPath) {
            String[] lines = fullDiff.split("\n");
            if (lines.length > MAX_DIFF_LINES) {
                fullDiff = String.join("\n", Arrays.copyOf(lines, MAX_DIFF_LINES))
                        + "\n\n... (差异过大，仅显示前 " + MAX_DIFF_LINES + " 行，请在终端查看完整 diff)";
            }
        }

        // stat 摘要
        List<String> statCmd = new ArrayList<>(Arrays.asList("git", "diff", "--stat"));
        if (hasPath) { statCmd.add("--"); statCmd.add(path); }
        ProcessResult statResult = runGit(workspaceDir, statCmd.toArray(new String[0]));

        List<String> statCachedCmd = new ArrayList<>(Arrays.asList("git", "diff", "--cached", "--stat"));
        if (hasPath) { statCachedCmd.add("--"); statCachedCmd.add(path); }
        ProcessResult statCachedResult = runGit(workspaceDir, statCachedCmd.toArray(new String[0]));

        String stat = statResult.stdout;
        if (!statCachedResult.stdout.isEmpty()) {
            stat += (stat.isEmpty() ? "" : "\n") + statCachedResult.stdout;
        }

        return new GitDiffContentDTO(fullDiff, stat);
    }

    /**
     * 获取 Git 仓库中指定版本的文件内容。
     */
    public GitFileContentDTO getFileContent(String workspaceHash, String path, String ref) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        if (path == null || path.contains("..") || path.startsWith("/")) {
            throw new ServiceException("Invalid path");
        }
        if (ref == null || ref.isEmpty()) ref = "HEAD";

        ProcessResult result = runGit(workspaceDir, "git", "show", ref + ":" + path);

        if (result.exitCode != 0) {
            throw new ServiceException("File not found: " + result.stderr);
        }

        return new GitFileContentDTO(result.stdout);
    }

    /**
     * 初始化 Git 仓库 —— git init + 自动生成 .gitignore + 可选初始提交。
     */
    public Map<String, Object> initRepo(String workspaceHash, Boolean initialCommit) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认不是已有仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode == 0) {
            throw new ServiceException("Already a git repository");
        }

        // 执行 git init
        ProcessResult initResult = runGit(workspaceDir, "git", "init");
        if (initResult.exitCode != 0) {
            throw new ServiceException("git init failed: " + initResult.stderr);
        }

        // 自动生成 .gitignore（仅当文件不存在时）
        File gitignore = new File(workspaceDir, ".gitignore");
        if (!gitignore.exists()) {
            Files.writeString(gitignore.toPath(), DEFAULT_GITIGNORE, StandardCharsets.UTF_8);
        }

        // 可选：执行 initial commit
        if (Boolean.TRUE.equals(initialCommit)) {
            runGit(workspaceDir, "git", "add", "-A");
            runGit(workspaceDir, "git", "-c", "user.name=Agent4j",
                    "-c", "user.email=agent4j@sorghum.site",
                    "commit", "-m", "Initial commit");
        }

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("initialized", true);

        ProcessResult branchResult = runGit(workspaceDir, "git", "branch", "--show-current");
        String branch = branchResult.stdout.trim();
        data.put("branch", branch.isEmpty() ? "master" : branch);

        return data;
    }

    /**
     * Git 提交 —— 解析 body 中的 message 和 files，支持精确文件列表或全量 add -A。
     */
    public GitCommitResultDTO commit(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认是 git 仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        // 解析 JSON body
        String message = null;
        List<String> files = null;
        if (body != null && !body.trim().isEmpty()) {
            try {
                ONode json = ONode.ofJson(body);
                if (json != null && json.isObject()) {
                    ONode msgNode = json.get("message");
                    if (msgNode != null && msgNode.isString()) {
                        message = msgNode.getString();
                    }
                    ONode filesNode = json.get("files");
                    if (filesNode != null && filesNode.isArray()) {
                        files = new ArrayList<>();
                        for (ONode f : filesNode.getArray()) {
                            files.add(f.getString());
                        }
                    }
                }
            } catch (Exception ignored) {
                log.debug("[git] 解析 commit body JSON 失败，使用默认值");
            }
        }

        if (message == null || message.trim().isEmpty()) {
            throw new ServiceException("Commit message is required");
        }

        // git add：有指定文件时精确暂存，否则只提交已暂存的文件
        if (files != null && !files.isEmpty()) {
            // 先清空暂存区，避免之前已暂存的非选中文件被一起提交
            runGit(workspaceDir, "git", "reset", "HEAD", "--");

            List<String> addCmd = new ArrayList<>();
            addCmd.add("git");
            addCmd.add("add");
            addCmd.add("--");
            addCmd.addAll(files);
            ProcessResult addResult = runGit(workspaceDir, addCmd.toArray(new String[0]));
            if (addResult.exitCode != 0) {
                throw new ServiceException("git add failed: " + addResult.stderr);
            }
        }

        // git commit
        ProcessResult commitResult = runGit(workspaceDir, "git",
                "-c", "user.name=Agent4j",
                "-c", "user.email=agent4j@sorghum.site",
                "commit", "-m", message);

        if (commitResult.exitCode != 0) {
            throw new ServiceException("git commit failed: " + commitResult.stderr);
        }

        return new GitCommitResultDTO(commitResult.stdout);
    }

    /**
     * 切换文件状态：未追踪 → 变更（git add），或变更 → 未追踪（git reset HEAD --）。
     */
    public Map<String, Object> toggleFile(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        String path = extractPath(body);
        if (path == null) {
            throw new ServiceException("Path is required");
        }

        // 检查文件当前状态
        ProcessResult statusResult = runGit(workspaceDir, "git", "status", "--porcelain", "--", path);
        String statusLine = statusResult.stdout.trim();

        ProcessResult result;
        String newState;

        if (statusLine.isEmpty() || statusLine.startsWith("M") || statusLine.startsWith("A") ||
                statusLine.startsWith("D") || statusLine.startsWith("R")) {
            // 已暂存或已追踪的变更 → 取消暂存
            result = runGit(workspaceDir, "git", "reset", "HEAD", "--", path);
            newState = "untracked";
        } else if (statusLine.startsWith("?")) {
            // 未追踪 → 暂存
            result = runGit(workspaceDir, "git", "add", "--", path);
            newState = "changed";
        } else {
            // 其他情况（如  M 未暂存修改）→ 暂存
            result = runGit(workspaceDir, "git", "add", "--", path);
            newState = "changed";
        }

        if (result.exitCode != 0) {
            throw new ServiceException("git toggle failed: " + result.stderr);
        }

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("path", path);
        data.put("newState", newState);
        return data;
    }

    /**
     * AI 自动生成 Git 提交消息 —— 获取当前变更及近 10 条提交日志，调用 LLM 生成。
     */
    public GitGenerateMessageDTO generateCommitMessage(String workspaceHash, String body) throws Exception {
        File workspaceDir = new File(resolveWorkspace(workspaceHash));

        // 安全校验：确认是 git 仓库
        ProcessResult check = runGit(workspaceDir, "git", "rev-parse", "--is-inside-work-tree");
        if (check.exitCode != 0) {
            throw new ServiceException("Not a git repository");
        }

        // 获取 AI 模型客户端
        ModelClient modelClient = agentService.getSharedModelClient();
        if (modelClient == null) {
            throw new ServiceException("AI 模型未配置，请先设置 OPENAI_API_KEY 环境变量");
        }

        // 解析可选的 files 参数
        List<String> files = null;
        if (body != null && !body.trim().isEmpty()) {
            try {
                ONode json = ONode.ofJson(body);
                if (json != null && json.isObject()) {
                    ONode filesNode = json.get("files");
                    if (filesNode != null && filesNode.isArray()) {
                        files = new ArrayList<>();
                        for (ONode f : filesNode.getArray()) {
                            files.add(f.getString());
                        }
                    }
                }
            } catch (Exception ignored) {
                log.debug("[git] 解析 generateCommitMessage body JSON 失败，使用默认值");
            }
        }

        // 1. 获取近 N 条提交日志（用于风格参考）
        String recentLog = runGitSimple(workspaceDir.getAbsolutePath(),
                "log", "--oneline", "-" + RECENT_COMMIT_LOG_COUNT);
        if (recentLog == null) recentLog = "";

        // 2. 获取变更（支持按文件过滤）
        String fullDiff;
        if (files != null && !files.isEmpty()) {
            // 仅获取选中文件的 diff
            StringBuilder sb = new StringBuilder();
            for (String f : files) {
                try {
                    ProcessResult sr = runGit(workspaceDir, "git", "diff", "--cached", "--", f);
                    if (sr.stdout != null && !sr.stdout.isEmpty()) sb.append(sr.stdout).append("\n");
                } catch (Exception ignored) {
                    log.debug("[git] 获取文件 {} 的 staged diff 失败", f);
                }
                try {
                    ProcessResult ur = runGit(workspaceDir, "git", "diff", "--", f);
                    if (ur.stdout != null && !ur.stdout.isEmpty()) sb.append(ur.stdout).append("\n");
                } catch (Exception ignored) {
                    log.debug("[git] 获取文件 {} 的 unstaged diff 失败", f);
                }
            }
            fullDiff = sb.toString().trim();
        } else {
            String stagedDiff = "";
            String unstagedDiff = "";
            try {
                ProcessResult sr = runGit(workspaceDir, "git", "diff", "--cached");
                stagedDiff = sr.stdout != null ? sr.stdout : "";
            } catch (Exception ignored) {
                log.debug("[git] 获取全局 staged diff 失败");
            }
            try {
                ProcessResult ur = runGit(workspaceDir, "git", "diff");
                unstagedDiff = ur.stdout != null ? ur.stdout : "";
            } catch (Exception ignored) {
                log.debug("[git] 获取全局 unstaged diff 失败");
            }
            fullDiff = (stagedDiff + "\n" + unstagedDiff).trim();
        }

        if (fullDiff.isEmpty()) {
            throw new ServiceException("没有待提交的变更");
        }

        // 截断 diff 防止超出模型上下文窗口
        if (fullDiff.length() > MAX_DIFF_CHARS) {
            fullDiff = fullDiff.substring(0, MAX_DIFF_CHARS)
                    + "\n\n... (diff 过长，已截断至前 " + MAX_DIFF_CHARS + " 字符)";
        }

        // 3. 构建 AI 提示词
        String systemPrompt = "你是一个 Git 提交消息生成助手。"
                + "根据 git diff 内容生成一条简洁、描述性的提交消息。"
                + "严格遵循以下规约：\n"
                + "- 参考「近 10 条提交」的风格（如前缀、格式、语言等）\n"
                + "- 消息长度不超过 72 字符（中文不超过 50 字）\n"
                + "- 使用中文或英文取决于近期提交的语言\n"
                + "- 仅输出提交消息本身，不要任何解释、引号或 markdown 格式";

        String userPrompt = "近 10 条提交（风格参考）：\n"
                + (recentLog.isEmpty() ? "（无历史提交）" : recentLog) + "\n\n"
                + "当前变更（git diff）：\n" + fullDiff + "\n\n"
                + "请生成提交消息：";

        // 4. 调用 AI 模型
        List<ChatMessage> messages = new ArrayList<>();
        messages.add(ChatMessage.system(systemPrompt));
        messages.add(ChatMessage.user(userPrompt));

        try {
            ONode response = modelClient.chat(messages, null);
            String content = response.get("content").getString();
            if (content == null || content.trim().isEmpty()) {
                throw new ServiceException("AI 未能生成提交消息");
            }
            // 清理多余的引号和空白
            String message = content.trim()
                    .replaceAll("^[\"']+|[\"']+$", "")
                    .replaceAll("^```[a-z]*\\s*|```$", "")
                    .trim();
            return new GitGenerateMessageDTO(message);
        } catch (Exception e) {
            log.error("[git] AI 生成提交消息失败: {}", e.getMessage());
            throw new ServiceException("AI 调用失败: " + e.getMessage());
        }
    }

    // ==================== 工具方法 ====================

    public String resolveWorkspace(String workspaceHash) {
        String workspacePath = agentService.resolveWorkspacePath(workspaceHash);
        if (workspacePath == null) workspacePath = agentService.getWorkspace();
        if (workspacePath == null) throw new ServiceException("未设置工作区");
        return workspacePath;
    }

    /**
     * 从 JSON 请求体中提取 path 字段。
     */
    private String extractPath(String body) {
        if (body == null || body.trim().isEmpty()) return null;
        try {
            ONode json = ONode.ofJson(body);
            if (json != null && json.isObject()) {
                ONode pathNode = json.get("path");
                if (pathNode != null && pathNode.isString()) {
                    String path = pathNode.getString();
                    if (path != null && !path.trim().isEmpty()
                            && !path.contains("..") && !path.startsWith("/")) {
                        return path;
                    }
                }
            }
        } catch (Exception ignored) {
            log.debug("[git] 解析 extractPath body JSON 失败");
        }
        return null;
    }

    /**
     * 简单 Git 命令执行 —— 用于只读查询，无超时控制。
     */
    private String runGitSimple(String dir, String... args) {
        try {
            List<String> cmd = new ArrayList<>();
            cmd.add("git");
            Collections.addAll(cmd, args);
            ProcessBuilder pb = new ProcessBuilder(cmd);
            pb.directory(new File(dir));
            pb.redirectErrorStream(false);
            Process proc = pb.start();

            StringBuilder stdout = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(proc.getInputStream(), StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (!stdout.isEmpty()) stdout.append('\n');
                    stdout.append(line);
                }
            }

            try (BufferedReader errReader = new BufferedReader(
                    new InputStreamReader(proc.getErrorStream(), StandardCharsets.UTF_8))) {
                while (errReader.readLine() != null) { /* drain */ }
            }

            int exit = proc.waitFor();
            if (exit != 0) return null;
            return stdout.toString();
        } catch (Exception e) {
            log.warn("[git] 执行失败: {}", e.getMessage());
            return null;
        }
    }

    /**
     * 增强 Git 命令执行 —— 带 10 秒超时保护、禁用终端交互提示。
     */
    private ProcessResult runGit(File workDir, String... command) throws Exception {
        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(workDir);
        pb.redirectErrorStream(false);
        pb.environment().put("GIT_TERMINAL_PROMPT", "0");

        Process proc = pb.start();
        String stdout = readStream(proc.getInputStream());
        String stderr = readStream(proc.getErrorStream());

        boolean finished = proc.waitFor(GIT_COMMAND_TIMEOUT_SEC, TimeUnit.SECONDS);
        if (!finished) {
            proc.destroyForcibly();
            ProcessResult result = new ProcessResult();
            result.exitCode = -1;
            result.stdout = "";
            result.stderr = "Command timed out after " + GIT_COMMAND_TIMEOUT_SEC + " seconds";
            return result;
        }

        ProcessResult result = new ProcessResult();
        result.exitCode = proc.exitValue();
        result.stdout = stdout;
        result.stderr = stderr;
        return result;
    }

    private String readStream(java.io.InputStream is) throws Exception {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
        }
        return sb.toString();
    }


}
