solon.app:
  name: "agent4j-web"
  group: "agent4j"
server:
  port: 8097

solon.logging:
  level: "DEBUG"
#添加MIME印射（如果有需要？）
solon.mime:
  json: "application/json"
knife4j.enable: true
knife4j.basic.enable: true
knife4j.basic.username: admin
knife4j.basic.password: 123456
knife4j.setting.enableOpenApi: false
knife4j.setting.enableSwaggerModels: false
knife4j.setting.enableFooter: false