version: '1.0'
name: branch-pipeline
displayName: Branch Pipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - .*
      exclude:
        - main
stages:
  - stage:
    name: verify
    displayName: Verify
    strategy: fast
    trigger: auto
    steps:
      - step: build@maven
        name: verify_maven
        displayName: Maven Verify
        jdkVersion: 17
        mavenVersion: 3.6.3
        commands:
          - mvn -B -ntp -gs .workflow/maven-central-settings.xml -s .workflow/maven-central-settings.xml clean verify
