version: '1.0'
name: electron-pipeline
displayName: Electron Package Pipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - main
stages:
  - stage:
    name: package
    displayName: Package Electron macOS + Windows + Linux
    strategy: fast
    trigger: auto
    steps:
      - step: build@nodejs
        name: package_electron_all
        displayName: Build Electron macOS + Windows + Linux Packages
        nodeVersion: 15.12.0
        commands:
          - bash .release/ci-package-electron.sh
        artifacts:
          - name: LOOPRA_ELECTRON_ALL
            path:
              - ./loopra-front/release
  - stage:
    name: publish
    displayName: Publish Electron Packages
    strategy: fast
    trigger: auto
    steps:
      - step: publish@general_artifacts
        name: upload_electron_all
        displayName: Upload Electron macOS + Windows + Linux Packages
        dependArtifact: LOOPRA_ELECTRON_ALL
        artifactRepository: default
        artifactName: loopra-electron-all
