version: '1.0'
name: main-pipeline
displayName: Main Pipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - main
stages:
  - stage:
    name: verify
    displayName: Verify
    strategy: fast
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven Verify and Package
        jdkVersion: 17
        mavenVersion: 3.6.3
        commands:
          - mvn -B -ntp clean verify
        artifacts:
          - name: DISTRIBUTION
            path:
              - ./loopra-web/target/loopra-web-dist.tar.gz
  - stage:
    name: publish
    displayName: Publish Artifact
    strategy: fast
    trigger: auto
    steps:
      - step: publish@general_artifacts
        name: publish_distribution
        displayName: Upload Distribution
        dependArtifact: DISTRIBUTION
        artifactRepository: default
        artifactName: loopra-web-dist
  - stage:
    name: release
    displayName: Release
    strategy: fast
    trigger: manual
    steps:
      - step: publish@release_artifacts
        name: release_distribution
        displayName: Create Release
        dependArtifact: loopra-web-dist
        artifactRepository: release
        version: '1.0.0.0'
        autoIncrement: true
