version: '1.0'
name: pr-pipeline
displayName: Pull Request Pipeline
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - main
stages:
  - stage:
    name: verify
    displayName: Verify
    strategy: fast
    trigger: auto
    steps:
      - step: build@maven
        name: verify_maven
        displayName: Maven Package (Skip Tests)
        jdkVersion: 17
        mavenVersion: 3.6.3
        commands:
          - mvn -B -ntp -DskipTests -gs .workflow/maven-central-settings.xml -s .workflow/maven-central-settings.xml clean verify
