<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>site.sorghum.agent</groupId>
        <artifactId>agent4j</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>agent4j-bin</artifactId>

    <dependencies>
        <dependency>
            <groupId>site.sorghum.agent</groupId>
            <artifactId>agent4j-tool</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-logging-logback</artifactId>
        </dependency>

        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-web</artifactId>
        </dependency>
        <!-- Solon IoC/AOP 容器 -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-lib</artifactId>
        </dependency>

        <!-- JSON 解析（snack4 + jsonpath） -->
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>snack4</artifactId>
            <version>4.0.49</version>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>snack4-jsonpath</artifactId>
            <version>4.0.49</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.36</version>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.noear</groupId>
                <artifactId>solon-maven-plugin</artifactId>
                <version>${solon.version}</version>
            </plugin>
        </plugins>
    </build>

</project>
